<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYN5bCNb\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYN5bCNb/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYN5bCNb.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYN5bCNb\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYN5bCNb\appAppKernelProdContainer([
    'container.build_hash' => 'YN5bCNb',
    'container.build_id' => '66b921a6',
    'container.build_time' => 1710496624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYN5bCNb');
